load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "iox_publisher",
    srcs = [
        "iox_publisher.cpp",
        "topic_data.hpp",
    ],
    deps = [
        "//iceoryx_posh",
    ],
)

cc_binary(
    name = "iox_publisher_untyped",
    srcs = [
        "iox_publisher_untyped.cpp",
        "topic_data.hpp",
    ],
    deps = [
        "//iceoryx_posh",
    ],
)

cc_binary(
    name = "iox_subscriber",
    srcs = [
        "iox_subscriber.cpp",
        "topic_data.hpp",
    ],
    deps = [
        "//iceoryx_posh",
    ],
)

cc_binary(
    name = "iox_subscriber_untyped",
    srcs = [
        "iox_subscriber_untyped.cpp",
        "topic_data.hpp",
    ],
    deps = [
        "//iceoryx_posh",
    ],
)
